#!/home/bendix/Documents/programming/python/numi-application/venv/bin/python

from PyQt5 import QtWidgets, QtCore
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtGui import *
import sys
from subprocess import check_output


class Window(QMainWindow):
    def __init__(self):
        super().__init__()

        self.setWindowTitle("Calculator")
        self.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        # self.setStyleSheet("border-radius: 50px")

        screen = app.primaryScreen()
        self.size = (screen.size().width(), screen.size().height())

        self.setGeometry(int(self.size[0]/2-200), int(self.size[1]/2-100), 400, 120)

        # Def Widgets
        self.label1_data = ""

        # Widgets
        self.label1 = QtWidgets.QLabel(self.label1_data, self)
        self.label1.move(0, 60)
        self.label1.resize(400, 40)
        self.label1.setAlignment(QtCore.Qt.AlignCenter)
        self.label1.setStyleSheet("font-size: 32px")

        self.input1 = QtWidgets.QLineEdit(self)
        self.input1.returnPressed.connect(self.numi_func)
        self.input1.resize(400, 50)
        self.input1.setStyleSheet("font-size: 20px")

        self.show()
        sys.exit(app.exec())

    def numi_func(self):
        input = f"{self.input1.text()}"
        output = check_output(["numi-cli", str(input)])
        self.label1.setText(output.decode("utf-8"))

app = QApplication(sys.argv)
window = Window()
